### ISSUE TITLE
Missing Assets Client

### ISSUE THREAD

**Issue by richardkeller411** [stackbithq/sourcebit-source-sanity#10]
On one build I have no problem and the ./assets/assetsClient is present in node modules on another build it is missing.   I copy over manually which shouldn't be required 

sourcebit-source-sanity\node_modules\@sanity\client\lib\sanityClient  is the module looking for it.

**Comment by eduardoboucas** [comment]
Hi @richardkeller411.

That sounds like a problem with the `@sanity/client` module, because we're not referencing that `assetsClient` file directly.

I have released a new version of the plugin (`0.4.1`), which contains the latest version of `@sanity/client`. Hopefully that will fix the problem. Please reopen the issue if not.

Thanks!
